### ISSUE TITLE
i18n help: translation lookup should work with draper/decorator

### ISSUE THREAD

**Issue by ccmcbeck** [bootstrap-ruby/rails-bootstrap-forms#192]
Great gem.  I'm using 

```
ruby '2.1.5'
gem 'rails', '4.2.0'
gem 'bootstrap_form', '2.2.0'
```

and trying to follow this pattern:

```
This gem is also aware of help messages in locale translation files (i18n):

en:
  activerecord:
    help:
      user:
        password: "A good password should be at least six characters long"
```

How do I tell the helper to perform the `i18n` lookup.  None of these work:

```
<%= f.password_field :password %>
<%= f.password_field :password, help: true %>
<%= f.password_field :password, help: :password %>
```

What am I missing?  This doesn't seem right:

```
<%= f.password_field :password, help: t('activerecord.help.user.password') %>
```

I looked at the `bootstrap-form` source and it doesn't seem to do anything special with the `help:` option so perhaps this is really a `rails` question, but I didn't find any clues in the rails i18n docs so I thought I'd start here.  Thanks in advance.
