### ISSUE TITLE
Radio buttons align incorrectly within form group

### ISSUE THREAD

**Issue by onebree** [bootstrap-ruby/rails-bootstrap-forms#244]
- Tested on v 2.1.1 and 2.3.0
- Tested with bootstrap sass v 3.1.1.1 and 3.3.4.1
- Rails 4.1.1
- Ruby 2.1.2
- Correctly installed the gem, along with LOC in `application.css.scss`

One of our company apps uses this gem. (Other apps use the updated versions I tested above, along with Rails 4.2.0). The only issue I have encountered can be seen below. The radio buttons should be moved several pixels to the right.

![screenshot from 2015-11-09 15 41 29](https://cloud.githubusercontent.com/assets/9038433/11045951/6dc68ae4-86f8-11e5-81cc-e31c022b588e.png)

Accompanying HAML code below:

``` haml
%h3 General Information
.panel.panel-default 
  .panel-body
    = f.form_group :customer_status, label: { text: 'Customer status' } do
      = f.radio_button :customer_status, 0, label: 'New customer', onClick: '$("#existing_customer").hide(500);', checked: @proposal.new_customer?
      = f.radio_button :customer_status, 1, label: 'Exisiting customer', onClick: '$("#existing_customer").hide(500);', checked: @proposal.existing_customer?
      = f.radio_button :customer_status, 2, label: 'Existing customer with new location', onClick: '$("#existing_customer").show(500);', checked: @proposal.existing_customer_new_location?
    #existing_customer{toggle_block(:existing_customer?)}
      = f.number_field :account_number
```

When I edit the padding and margins in dev tools, I see that such changes affect regular check boxes as well. I only want to change the properties of radio buttons for this to work. Here are the stats, FWIW:

```
element {               inline
}
.radio, .checkbox {     application.css:3589
    display: block;
    min-height: 20px;
    margin-top: 10px;
    margin-bottom: 10px;
}
```

And the following are from the `application.css` stylesheet that the dev tools point to. (The values are the same when I update bootstrap sass or forms)

``` css
/* line 208, /home/hstevens/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bootstrap-sass-3.1.1.1/vendor/assets/stylesheets/bootstrap/_forms.scss */
.radio,
.checkbox {
  display: block;
  min-height: 20px;
  margin-top: 10px;
  margin-bottom: 10px;
}
/* line 214, /home/hstevens/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bootstrap-sass-3.1.1.1/vendor/assets/stylesheets/bootstrap/_forms.scss */
.radio label,
.checkbox label {
  padding-left: 20px;
  margin-bottom: 0;
  font-weight: normal;
  cursor: pointer;
}

/* line 224, /home/hstevens/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bootstrap-sass-3.1.1.1/vendor/assets/stylesheets/bootstrap/_forms.scss */
.radio input[type="radio"],
.radio-inline input[type="radio"],
.checkbox input[type="checkbox"],
.checkbox-inline input[type="checkbox"] {
  float: left;
  margin-left: -20px;
}

/* line 229, /home/hstevens/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bootstrap-sass-3.1.1.1/vendor/assets/stylesheets/bootstrap/_forms.scss */
.radio + .radio,
.checkbox + .checkbox {
  margin-top: -5px;
}
```

**Comment by onebree** [comment]
**UPDATE** - in order to achieve the desired result (buttons aligned with form-group label), I added the following to `application.css.scss`:

```css
.radio {
  margin-left: 20px;
}
```

If others have this issue, I will gladly submit a pull request; however, as I noted before, other apps we have do not experience this.
